version: 2

# Strategy
# 1. Fetch the remote repository of the acceptance suite, git fetch or clone our repo
# 2. Run all the nightly images (influxdb, telegraf) from quayi 
#   2.1. Save on docker compose by using the trick "--net host" and "machine: true", found in litmus
#   2.2. -v /var/run/docker.sock:/var/run/docker.sock, this will fix issue with connection to Docker
#   2.3. entryppoint with e2e testing w/o new Dockerfile
# 3. Run the acceptance suite, build reports
# 4. Map the reports to the output artifacts

jobs:
  accsuite:
    machine: 
      image: ubuntu-1604:201903-01
    steps:
      - attach_workspace:
          at: ~/project
      - checkout
      - run: ./install-chromium.sh
      - run: ./checkout-acceptance-suite.sh
      - run: ./install-nvm.sh
      - run: ./configure-test-suite.sh
      - run: cd ./selenium-accept-infl2 && mkdir -p screenshots/test && echo "test.txt" > screenshots/test/test.txt
      - run: ls -al
      - run: chromium-browser --version
        #      - run: docker run --net host --name influx-v2 quay.io/influxdb/influx:nightly /entrypoint.sh influxd --e2e-testing=true &
      - run: ./run-test.sh
        #      - run: . ./env && $MYNODE src/utils/htmlReport.js
        #node src/utils/junitReport.js
      - store_artifacts: 
          path: ./selenium-accept-infl2/screenshots
      - store_artifacts: 
          path: ./selenium-accept-infl2/report
  imagecheck:
    machine:
      image: circleci/node:13.8-stretch
    steps: 
      - run: google-chrome --version && which google-chrome && chromedriver --version && which chromedriver    
workflows:
  version: 2
  build:
    jobs:
      - imagecheck

